# Generated by Django 2.2.24 on 2021-09-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0002_employee_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='pic',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='salaire',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='téléphone',
        ),
    ]
