# Generated by Django 2.2.24 on 2021-09-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0003_auto_20210910_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='téléphone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='photo',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salaire',
            new_name='salary',
        ),
    ]
